version: 2
updates:
<<<<<<< HEAD
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/stack"
    schedule:
      interval: "weekly"

=======
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /test
    schedule:
      interval: daily
>>>>>>> origin/main
