package cmd

import (
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// stackDir and envsDir define the terraform project layout for this repo.
// Note: no "terraform/" prefix — stack and envs live at the repo root level.
const (
	stackDirName = "stack"
	envsDirName  = "envs"
)

// repoRoot returns the absolute path to the repository root by walking up
// from the current working directory until it finds a .git marker.
func repoRoot() (string, error) {
	dir, err := filepath.Abs(".")
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, ".git")); err == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("not inside a git repository (no .git found walking up from %s)", dir)
		}
		dir = parent
	}
}

// stackDir returns the absolute path to the terraform stack directory.
func stackDir() (string, error) {
	root, err := repoRoot()
	if err != nil {
		return "", err
	}
	return filepath.Join(root, stackDirName), nil
}

// backendArgs builds the -backend-config flags for terraform init.
// The env-specific envs/<env>/backend.hcl supplies the per-environment state
// key, bucket, and DynamoDB table (all managed by bootstrap / platform-org).
// If stack/backend.local.hcl exists (gitignored, operator override) it is
// prepended; later flags take precedence in Terraform so the env key always wins.
func backendArgs(stackPath, root, env string) []string {
	envsBackend := filepath.Join(root, envsDirName, env, "backend.hcl")
	relEnvs, err := filepath.Rel(stackPath, envsBackend)
	if err != nil {
		relEnvs = filepath.Join("..", envsDirName, env, "backend.hcl")
	}

	args := []string{"-backend-config=" + relEnvs}

	local := filepath.Join(stackPath, "backend.local.hcl")
	if _, err := os.Stat(local); err == nil {
		args = append([]string{"-backend-config=backend.local.hcl"}, args...)
	}

	return args
}

// varFileArgs returns the -var-file flags for terraform plan/apply/destroy.
// Both the committed terraform.tfvars and the fetched.auto.tfvars.json
// (generated by platform-bootstrap) are included only when present.
func varFileArgs(stackPath, root, env string) []string {
	envsDir := filepath.Join(root, envsDirName, env)

	relPath := func(name string) string {
		abs := filepath.Join(envsDir, name)
		rel, err := filepath.Rel(stackPath, abs)
		if err != nil {
			rel = filepath.Join("..", envsDirName, env, name)
		}
		return "-var-file=" + rel
	}

	var args []string

	// terraform.tfvars is optional; only include when the file exists.
	tfvarsAbs := filepath.Join(envsDir, "terraform.tfvars")
	if _, err := os.Stat(tfvarsAbs); err == nil {
		args = append(args, relPath("terraform.tfvars"))
	}

	// fetched.auto.tfvars.json is generated by platform-bootstrap; include only if present.
	fetchedAbs := filepath.Join(envsDir, "fetched.auto.tfvars.json")
	if _, err := os.Stat(fetchedAbs); err == nil {
		args = append(args, relPath("fetched.auto.tfvars.json"))
	}

	return args
}

// envSentinelPath returns the path of the file that records the last
// environment for which terraform init was run in stackPath.
func envSentinelPath(stackPath string) string {
	return filepath.Join(stackPath, ".terraform", "last-env")
}

// isInitialisedForEnv reports whether terraform has been initialised for the
// given environment in the stack directory. It checks both that .terraform/
// exists and that the recorded last-env matches the requested env.
func isInitialisedForEnv(stackPath, env string) bool {
	data, err := os.ReadFile(envSentinelPath(stackPath))
	if err != nil {
		return false
	}
	return strings.TrimSpace(string(data)) == env
}

// recordInitEnv persists env to the sentinel file so subsequent calls to
// isInitialisedForEnv can skip a redundant terraform init.
func recordInitEnv(stackPath, env string) error {
	path := envSentinelPath(stackPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("ensuring .terraform directory exists: %w", err)
	}
	return os.WriteFile(path, []byte(env), 0o600)
}

// runOptions configures a terraform subprocess invocation.
type runOptions struct {
	stackPath string
	args      []string
	creds     rawCreds
	stdin     io.Reader // nil for non-interactive; os.Stdin for interactive
	stdout    io.Writer // defaults to os.Stdout
	stderr    io.Writer // defaults to os.Stderr
}

// runTerraform executes terraform with the given args in stackPath, streaming
// output to the terminal. Returns terraform's exit code directly.
//
// Exit code 2 from plan means "changes present" — callers must treat this as
// a non-error condition.
func runTerraform(ctx context.Context, opts runOptions) (int, error) {
	if opts.stdout == nil {
		opts.stdout = os.Stdout
	}
	if opts.stderr == nil {
		opts.stderr = os.Stderr
	}

	cmd := exec.CommandContext(ctx, "terraform", opts.args...) //nolint:gosec
	cmd.Dir = opts.stackPath

	// Build subprocess env: parent env + injected AWS creds.
	env := os.Environ()
	for k, v := range opts.creds.toEnv() {
		env = append(env, k+"="+v)
	}
	cmd.Env = env

	cmd.Stdin = opts.stdin
	cmd.Stdout = opts.stdout
	cmd.Stderr = opts.stderr

	if err := cmd.Run(); err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			return exitErr.ExitCode(), nil
		}
		return -1, fmt.Errorf("running terraform: %w", err)
	}
	return 0, nil
}

// terraformInit runs terraform init in the given stack directory.
func terraformInit(ctx context.Context, stackPath, root, env string, creds rawCreds) error {
	args := append([]string{"init"}, backendArgs(stackPath, root, env)...)
	code, err := runTerraform(ctx, runOptions{
		stackPath: stackPath,
		args:      args,
		creds:     creds,
	})
	if err != nil {
		return err
	}
	if code != 0 {
		return fmt.Errorf("terraform init exited with code %d", code)
	}
	if err := recordInitEnv(stackPath, env); err != nil {
		return fmt.Errorf("recording init env: %w", err)
	}
	return nil
}

// ensureInit runs terraform init if the stack has not been initialised for
// the requested env. Re-init is triggered when the environment changes so
// that the correct backend (state bucket/key) is always configured.
func ensureInit(ctx context.Context, stackPath, root, env string, creds rawCreds) error {
	if isInitialisedForEnv(stackPath, env) {
		return nil
	}
	d.log.Info("initialising stack for environment", "stack", stackPath, "env", env)
	return terraformInit(ctx, stackPath, root, env, creds)
}

func terraformCommandError(stdout, stderr string) string {
	if msg := strings.TrimSpace(stderr); msg != "" {
		return msg
	}
	if msg := strings.TrimSpace(stdout); msg != "" {
		return msg
	}
	return "no output"
}
