name: Terraform Destroy (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment to destroy"
        options:
          - staging
          - prod
        required: true
      confirm:
        type: string
        description: 'Type "DESTROY" to confirm'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    if: vars.TERRAFORM_DESTROY_ENABLED != 'false'
    uses: FelipeFuhr/ffreis-workflows-terraform/.github/workflows/tf-destroy.yml@e0cd54322d52fe7c522dd0bc2c46d56df2ceae43
    with:
      environment: ${{ github.event.inputs.environment }}
      chdir: "infra/stack"
      confirm: ${{ github.event.inputs.confirm }}
    secrets: inherit
